import OAI.MeasureTheory.Falconer.Geometry.PlanarProjectionCoordinates

namespace OAI

/-! Geometry of the fractional-linear direction map generated by two
projection bases. All constants depend only on their separation. -/
namespace Falconer

noncomputable def projectionRatio (a b y : ℝ) : ℝ := (y-a)/(b-y)

 theorem projectionRatio_difference {a b y z : ℝ} (hy : y ≠ b) (hz : z ≠ b) :
    (projectionRatio a b y-projectionRatio a b z)*(b-y)*(b-z) = (b-a)*(y-z) := by
  have hy' : b-y ≠ 0 := sub_ne_zero.mpr hy.symm
  have hz' : b-z ≠ 0 := sub_ne_zero.mpr hz.symm
  unfold projectionRatio
  field_simp
  ring

 theorem projectionRatio_injOn {a b : ℝ} (hab : b ≠ a) :
    Set.InjOn (projectionRatio a b) {y : ℝ | y ≠ b} := by
  intro y hy z hz he
  have hh := projectionRatio_difference (a := a) hy hz
  rw [he,sub_self,zero_mul,zero_mul] at hh
  have hba : b-a ≠ 0 := sub_ne_zero.mpr hab
  exact sub_eq_zero.mp ((mul_eq_zero.mp hh.symm).resolve_left hba)

 theorem projectionRatio_inverse_bound {a b y z : ℝ} (hab : b ≠ a)
    (hy : y ≠ b) (hz : z ≠ b) (hb : |b| ≤ 1) (hy1 : |y| ≤ 1) (hz1 : |z| ≤ 1) :
    |y-z| ≤ (4/|b-a|)*|projectionRatio a b y-projectionRatio a b z| := by
  have hsep : 0 < |b-a| := abs_pos.mpr (sub_ne_zero.mpr hab)
  have hby : |b-y| ≤ 2 := (abs_sub b y).trans (by linarith)
  have hbz : |b-z| ≤ 2 := (abs_sub b z).trans (by linarith)
  have hh := congrArg abs (projectionRatio_difference (a := a) hy hz)
  simp only [abs_mul] at hh
  have hp : |b-y| * |b-z| ≤ 4 := by nlinarith [abs_nonneg (b-y),abs_nonneg (b-z)]
  have hm := mul_le_mul_of_nonneg_left hp (abs_nonneg (projectionRatio a b y-projectionRatio a b z))
  have hnum : |y-z| * |b-a| ≤ 4*|projectionRatio a b y-projectionRatio a b z| := by nlinarith
  have he : (4/|b-a|)*|projectionRatio a b y-projectionRatio a b z| =
      (4*|projectionRatio a b y-projectionRatio a b z|)/|b-a| := by ring
  rw [he]
  exact (le_div_iff₀ hsep).2 hnum

end Falconer

end OAI
