import OAI.MeasureTheory.Falconer.Estimates.DyadicTree
import OAI.MeasureTheory.Falconer.Estimates.SphericalEnergy

namespace OAI

/-! # The actual dyadic cell-pair exclusion generated by heavy affine plates -/

namespace Falconer
open Set MeasureTheory
open scoped ENNReal
variable {d : ℕ}

def HeavyPlateHits (ρ : Measure (Space d)) (P Q : DyadicCube d) (r m : ℝ) : Prop :=
  ∃ w : Space d, ‖w‖ = 1 ∧ ∃ a : ℝ,
    ENNReal.ofReal m ≤ ρ {x | |inner ℝ w x-a| ≤ r} ∧
    (∃ x ∈ P.carrier, |inner ℝ w x-a| ≤ r) ∧
    (∃ x ∈ Q.carrier, |inner ℝ w x-a| ≤ r)

noncomputable def heavyPlateCellPairs (ρ : Measure (Space d)) (Q : DyadicCube d)
    (j : ℕ) (r m : ℝ) : Set (Space d × Space d) := by
  classical
  exact ⋃ pq ∈ (cubePaths d j).product (cubePaths d j),
    if HeavyPlateHits ρ (Q.descendant pq.1) (Q.descendant pq.2) r m then
      (Q.descendant pq.1).carrier ×ˢ (Q.descendant pq.2).carrier else ∅

theorem measurableSet_heavyPlateCellPairs (ρ : Measure (Space d)) (Q : DyadicCube d)
    (j : ℕ) (r m : ℝ) : MeasurableSet (heavyPlateCellPairs ρ Q j r m) := by
  classical
  apply MeasurableSet.iUnion
  intro pq
  apply MeasurableSet.iUnion
  intro _
  split_ifs
  · exact (Q.descendant pq.1).measurable.prod (Q.descendant pq.2).measurable
  · exact MeasurableSet.empty

theorem mem_heavyPlateCellPairs_iff (ρ : Measure (Space d)) (Q : DyadicCube d)
    (j : ℕ) (r m : ℝ) (x y : Space d) :
    (x,y) ∈ heavyPlateCellPairs ρ Q j r m ↔
      ∃ p ∈ cubePaths d j, ∃ q ∈ cubePaths d j,
        HeavyPlateHits ρ (Q.descendant p) (Q.descendant q) r m ∧
        x ∈ (Q.descendant p).carrier ∧ y ∈ (Q.descendant q).carrier := by
  classical
  constructor
  · intro h
    obtain ⟨⟨p,q⟩,hpq,h⟩ := mem_iUnion₂.mp h
    obtain ⟨hp,hq⟩ := Finset.mem_product.mp hpq
    split_ifs at h with hhit
    · exact ⟨p,hp,q,hq,hhit,h⟩
    · exact h.elim
  · rintro ⟨p,hp,q,hq,hhit,hx,hy⟩
    exact mem_iUnion₂.mpr ⟨(p,q),Finset.mem_product.mpr ⟨hp,hq⟩,
      by rw [ite_eq_left hhit]; exact ⟨hx,hy⟩⟩

theorem heavyPlateCellPairs_subset_root (ρ : Measure (Space d)) (Q : DyadicCube d)
    (j : ℕ) (r m : ℝ) : heavyPlateCellPairs ρ Q j r m ⊆ Q.carrier ×ˢ Q.carrier := by
  rintro ⟨x,y⟩ h
  obtain ⟨p,_,q,_,_,hx,hy⟩ := (mem_heavyPlateCellPairs_iff ρ Q j r m x y).mp h
  exact ⟨Q.descendant_subset p hx,Q.descendant_subset q hy⟩

theorem heavyPlateCellPairs_of_points (ρ : Measure (Space d)) (Q : DyadicCube d)
    (j : ℕ) (r m : ℝ) {x y w : Space d} {a : ℝ}
    (hx : x ∈ Q.carrier) (hy : y ∈ Q.carrier) (hw : ‖w‖ = 1)
    (hm : ENNReal.ofReal m ≤ ρ {z | |inner ℝ w z-a| ≤ r})
    (hxw : |inner ℝ w x-a| ≤ r) (hyw : |inner ℝ w y-a| ≤ r) :
    (x,y) ∈ heavyPlateCellPairs ρ Q j r m := by
  obtain ⟨p,hp,hxp⟩ := Q.mem_descendant_at_depth j hx
  obtain ⟨q,hq,hyq⟩ := Q.mem_descendant_at_depth j hy
  exact (mem_heavyPlateCellPairs_iff ρ Q j r m x y).mpr
    ⟨p,hp,q,hq,⟨w,hw,a,hm,⟨x,hxp,hxw⟩,y,hyq,hyw⟩,hxp,hyq⟩

end Falconer

end OAI
